version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fastapidb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./  :/code/firebase-creds.json:ro
    environment:
      DATABASE_URL: postgresql://fastapi:secret@db:5432/fastapidb
      FIREBASE_CREDENTIALS: /code/firebase-creds.json
      FIREBASE_STORAGE_BUCKET: onaitabu.firebasestorage.app
    depends_on:
      - db
    restart: always

volumes:
  dbdata:
