version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fastapidb
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://fastapi:secret@db:5432/fastapidb
    depends_on: [db]
    expose:
      - "8000"        # внутренний порт
    restart: always

volumes:
  dbdata:
