name: Deploy to Droplet

on:
  push:
    branches:
      - main  # отслеживаем пуши в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key for deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # использует секрет из GitHub

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no deploy@<server_ip> << 'EOF'
          cd /srv/fastapi || exit  # переходим в каталог с проектом
          git pull origin main || exit  # забираем последние изменения из репозитория
          docker compose pull || exit  # обновляем образы
          docker compose up -d --remove-orphans || exit  # перезапускаем контейнеры
        EOF
